version: "3"
services: 
    web:
        image: node-api
        build: .
        command: "npm start"
        ports:
            - "4001:4000"
        depends_on: 
            - "mongo"
    mongo:
        image: mongo
        ports: 
            - "27018:27017"
